11 get reviews query refactor
cthrnsdlr/NC-bend-project pull request #14
Opened 2022-11-16 10:43 UTC by cthrnsdlr

2022-11-16 12:19 UTC, Rayhaan2k9 requested changes
A couple of bits to add Catherine. Once fixed, please resubmit this PR 🙂

2022-11-16 12:19 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +      });
☝️ This test does the same as the test above as you are just testing a different column. Is the first test passes, the second one will pass as well :)

2022-11-16 12:19 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +      });
Same with this test. We already have a similar test just above it :)

2022-11-16 12:19 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +      });
Need a few more tests here. 

- What if the category is invalid for example `category=1234` 
- What if the category is valid but doesn't exist in db? eg. `category=banana`
- What if the category exists but has no reviews associated with it?

2022-11-16 12:23 UTC, CatherineSadler commented on __tests__/app.test.js
> +      });
initially one test was passing and one was failing because of how sql sorts whitespace, so i left those in to check if the fix i put in didnt break number sorting too

2022-11-17 11:24 UTC, Rayhaan2k9 approved these changes
Amazing! 👏

2022-11-17 11:46 UTC, merged